name: Deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli
    - name: Install dependencies
      run: yarn
    - name: Deploy
      run: |
        git config --global user.name "Github Actions"
        yarn deploy
      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: [ dev ]
